[package]
name = "nn-fuse"
version = "0.1.0"
authors = ["Raytwo <raytwo@arcropolis.com>, blujay <the.blu.dev@gmail.com>"]
edition = "2018"

[dependencies]
skyline = { git = "https://github.com/Raytwo/skyline-rs", branch="preview" }
